services:
  - type: web
    name: voidrunner
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
